//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncodingConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EncodingConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;saved file ?.
        /// </summary>
        internal static string CheckBox_OpenSavedFile {
            get {
                return ResourceManager.GetString("CheckBox_OpenSavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.*.
        /// </summary>
        internal static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Ala Ibrahim Hadid 2009 - 2015
        ///
        ///AHD Encoding Converter is a part of AHD Subtitles Maker Professional.
        ///AHD Subtitles Maker Professional is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///AHD Subtitles Maker Professional is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Message_About {
            get {
                return ResourceManager.GetString("Message_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse where you want to save the file.
        /// </summary>
        internal static string Message_BrowseWhereYouWantToSaveTheFile {
            get {
                return ResourceManager.GetString("Message_BrowseWhereYouWantToSaveTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done !!.
        /// </summary>
        internal static string Message_Done {
            get {
                return ResourceManager.GetString("Message_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the file you want to convert encoding for.
        /// </summary>
        internal static string Message_OpenTheFileYouWantToConvertEncodingFor {
            get {
                return ResourceManager.GetString("Message_OpenTheFileYouWantToConvertEncodingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse for input file first !.
        /// </summary>
        internal static string Message_PleaseBrowseForInputFileFirst {
            get {
                return ResourceManager.GetString("Message_PleaseBrowseForInputFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse where to save the file first !.
        /// </summary>
        internal static string Message_PleaseBrowseWhereToSaveTheFileFirst {
            get {
                return ResourceManager.GetString("Message_PleaseBrowseWhereToSaveTheFileFirst", resourceCulture);
            }
        }
    }
}
