//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncodingConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EncodingConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;saved file ?.
        /// </summary>
        internal static string CheckBox_OpenSavedFile {
            get {
                return ResourceManager.GetString("CheckBox_OpenSavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Encoding_Converter_32x32 {
            get {
                object obj = ResourceManager.GetObject("Encoding_Converter_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon_Encoding_Converter_32x32 {
            get {
                object obj = ResourceManager.GetObject("Icon_Encoding_Converter_32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:{0}
        ///Created by Ammar J. Alhamwi
        ///
        ///Inspired by &quot;AHD Encoding Converter&quot; by Ala Ibrahim Hadid.
        ///Encoding Converter is distributed AS IS in the hope that it will be useful, but WITHOUT ANY WARRANTY..
        /// </summary>
        internal static string Message_About {
            get {
                return ResourceManager.GetString("Message_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse where you want to save the file.
        /// </summary>
        internal static string Message_BrowseWhereYouWantToSaveTheFile {
            get {
                return ResourceManager.GetString("Message_BrowseWhereYouWantToSaveTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done !!.
        /// </summary>
        internal static string Message_Done {
            get {
                return ResourceManager.GetString("Message_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing input file caused an error because input file &apos;{0}&apos; was not found!.
        /// </summary>
        internal static string Message_Err_ChangeInputFile_FileNotFound {
            get {
                return ResourceManager.GetString("Message_Err_ChangeInputFile_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing of input file to &apos;{0}&apos; caused an unspecified error!.
        /// </summary>
        internal static string Message_Err_ChangeInputFile_UnspecifiedError {
            get {
                return ResourceManager.GetString("Message_Err_ChangeInputFile_UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t complete the conversion because of the following error:.
        /// </summary>
        internal static string Message_Err_ConversionFailedForTheFollowingError {
            get {
                return ResourceManager.GetString("Message_Err_ConversionFailedForTheFollowingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection of input encoding didn&apos;t succeed because input file &apos;{0}&apos; was not found!.
        /// </summary>
        internal static string Message_Err_DetectInputEncodingFailed_InputFileNotFound {
            get {
                return ResourceManager.GetString("Message_Err_DetectInputEncodingFailed_InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection of input encoding didn&apos;t succeed because of unspecified error!.
        /// </summary>
        internal static string Message_Err_DetectInputEncodingFailed_UnspecifiedError {
            get {
                return ResourceManager.GetString("Message_Err_DetectInputEncodingFailed_UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program doesn&apos;t have the permission to perform the conversion..
        /// </summary>
        internal static string Message_Err_NoPermissionToPerformConversion {
            get {
                return ResourceManager.GetString("Message_Err_NoPermissionToPerformConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided input file does not exsist!.
        /// </summary>
        internal static string Message_InputFileDoesNotExsist {
            get {
                return ResourceManager.GetString("Message_InputFileDoesNotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the file you want to convert encoding for.
        /// </summary>
        internal static string Message_OpenTheFileYouWantToConvertEncodingFor {
            get {
                return ResourceManager.GetString("Message_OpenTheFileYouWantToConvertEncodingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse for input file first !.
        /// </summary>
        internal static string Message_PleaseBrowseForInputFileFirst {
            get {
                return ResourceManager.GetString("Message_PleaseBrowseForInputFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse where to save the file first !.
        /// </summary>
        internal static string Message_PleaseBrowseWhereToSaveTheFileFirst {
            get {
                return ResourceManager.GetString("Message_PleaseBrowseWhereToSaveTheFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to copy error details to clipboard?.
        /// </summary>
        internal static string Message_Q_Error_DoYouWantToCopyErrorMessage {
            get {
                return ResourceManager.GetString("Message_Q_Error_DoYouWantToCopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string Message_Q_OutputFileAlreadyExists_Overwrite {
            get {
                return ResourceManager.GetString("Message_Q_OutputFileAlreadyExists_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
